[package]
name = "wgpu-rs-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.9.0"
tokio = { version = "1", features = ["full"] }
winit = "0.25"
futures = "0.3"